/* eslint-disable */
import { validateAccessToken } from './dist/modules/auth/services/auth.service.js';
import dotenv from 'dotenv';
dotenv.config();

const token = "eyJhbGciOiJFUzI1NiIsImtpZCI6ImY0MzcwMDVmLWM0ZTEtNGVmMC1iNjNiLTFlMDkwMWJkYWU2MyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL21kd3J5aHhucnVwcnR1cW9uYnd5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyOWMyMmZlMi02ODM1LTRmODktOWVhZi0zMWNmMzI1OWViMmQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyMDQwMzcxLCJpYXQiOjE3ODIwMzY3NzEsImVtYWlsIjoidGVzdGNhZmUub3duZXJAdGVzdC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJicmFuY2hfaWRzIjpbIjM1ODE3YmVkLWYxNGYtNGNmZi1iNTEwLTI0N2E4YTc0MGJlYiJdLCJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl0sInJiYWNfcm9sZSI6IlJFU1RBVVJBTlRfQURNSU4iLCJ0ZW5hbnRfaWQiOiIwNjQ0YjdmZi1jNWE1LTRjMWQtOWE5NS1kZTIyOTE1ZTM3ZjkifSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODIwMzY3NzF9XSwic2Vzc2lvbl9pZCI6ImRiZTRkZWZkLWI4NGMtNDMxZi05NmU4LTNhYWU5ZTgyYmExNiIsImlzX2Fub255bW91cyI6ZmFsc2V9.DOrk4yrG3-RgsWoNB_aRL6VgE_-R8xvJHTcfTtJ1dgEBV2rkl5Z0UQezVKFzlgbCihbtDpGGUpX3QGiUtrG";

async function run() {
  const result = await validateAccessToken(token);
  console.log("Validation Result:", result);
}
run().catch(console.error);
